---
- hosts: docker 
  tasks:
  - name: install docker repo
    get_url:
      url: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm
      dest: /root
  - name: install docker -ce
    yum:
      name: docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm 
      state: present
         
