---
- hosts: docker 
  tasks:
  - name: install docker repo
    yum_repository:
      name: yum repo
      description: Some YUM repo
      baseurl: https://yum.dockerproject.org/repo/main/centos/7/
      gpgkey: https://yum.dockerproject.org/gpg
      reposdir:
  - name: install docker -ce
    yum:
      name: docker-engine
      state: present
  - name: service start
    systemd:
      name: docker.service 
      enabled: yes
      masked: no
  - name: start service
    systemd:
      name: docker
      state: started
      enabled: True
