---
#this is my frist ansible demo
- hosts: all
  become: yes
- tasks:
  - name: install httpd server
    yum:
    name: httpd
    state: present
  - name: service start
    service:
    name: httpd
    state: started
    enabled: yes
